# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "77199a97d4c12ee04a1a942ce6464934"
name = "COD Smart Rules"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobjects,write_metaobject_definitions,read_metaobjects,read_products,read_customers,read_orders,read_payment_customizations,write_payment_customizations"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"
