// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/payment-customization-activate": {
    params: {};
  };
  "/api/debug/payment-customizations": {
    params: {};
  };
  "/api/payment-customization-create": {
    params: {};
  };
  "/api/payment-customization-update": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/api/rules/set-active": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/rules": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/api/payment-customization-activate" | "/api/debug/payment-customizations" | "/api/payment-customization-create" | "/api/payment-customization-update" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/api/rules/set-active" | "/auth/login" | "/auth/*" | "/app" | "/app/additional" | "/app/rules";
  };
  "routes/api.payment-customization-activate.jsx": {
    id: "routes/api.payment-customization-activate";
    page: "/api/payment-customization-activate";
  };
  "routes/api.debug.payment-customizations.jsx": {
    id: "routes/api.debug.payment-customizations";
    page: "/api/debug/payment-customizations";
  };
  "routes/api.payment-customization-create.jsx": {
    id: "routes/api.payment-customization-create";
    page: "/api/payment-customization-create";
  };
  "routes/api.payment-customization-update.jsx": {
    id: "routes/api.payment-customization-update";
    page: "/api/payment-customization-update";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/api.rules.set-active.jsx": {
    id: "routes/api.rules.set-active";
    page: "/api/rules/set-active";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/additional" | "/app/rules";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.rules.jsx": {
    id: "routes/app.rules";
    page: "/app/rules";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/api.payment-customization-activate": typeof import("./app/routes/api.payment-customization-activate.jsx");
  "routes/api.debug.payment-customizations": typeof import("./app/routes/api.debug.payment-customizations.jsx");
  "routes/api.payment-customization-create": typeof import("./app/routes/api.payment-customization-create.jsx");
  "routes/api.payment-customization-update": typeof import("./app/routes/api.payment-customization-update.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/api.rules.set-active": typeof import("./app/routes/api.rules.set-active.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "routes/app.rules": typeof import("./app/routes/app.rules.jsx");
};