api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "cod-rules-payment"
type = "function"
uid = "a7202707-b80a-6aaf-bb0c-26e8ae38622a8926991b"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/cart_payment_methods_transform_run.graphql"
  export = "cart_payment_methods_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/cod-rules-payment.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
